### ISSUE TITLE
WeatherRepository contains application key

### ISSUE THREAD

**Issue by atoivonen** [RossSickora/awesome-weather-console#2]
Could this be refactored to make the application key configurable outside of source code?

**Comment by RossSickora** [comment]
heck yeah it could! we could put it in a properties file (not my preferred solution), or possibly a remote configuration tool for managing environment based variables such as this, but in this case I thought this implementation was sufficient.  let me know your thoughts.

**Comment by RossSickora** [comment]
Went ahead and tossed the apikey in a properties file.
